# Generated by Django 4.0.4 on 2022-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('status', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='job_posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=300)),
                ('salary_expected', models.IntegerField()),
                ('timing', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_details', models.CharField(max_length=300)),
                ('job_applied_id', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
    ]
