# Generated by Django 4.0.4 on 2022-05-13 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_job_applied_job_posting_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='temp.job_posting'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='temp.company'),
        ),
    ]
