# Generated by Django 4.0.4 on 2022-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='qualification',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='work_experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
