# Generated by Django 4.0.4 on 2022-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0006_alter_job_posting_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='status',
            field=models.CharField(default='PENDING', max_length=400),
        ),
    ]
