# Generated by Django 4.0.4 on 2022-06-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0007_alter_job_applied_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('gender', models.CharField(max_length=400)),
                ('phonenumber', models.CharField(max_length=400)),
                ('github', models.CharField(max_length=400)),
                ('linkdin', models.CharField(max_length=400)),
                ('skills', models.CharField(max_length=1000)),
                ('aboutyou', models.CharField(max_length=1000)),
                ('tenthschool', models.CharField(max_length=400)),
                ('tenthpassing', models.CharField(max_length=400)),
                ('tenthpercent', models.CharField(max_length=400)),
                ('twelveschool', models.CharField(max_length=400)),
                ('twelvepassing', models.CharField(max_length=400)),
                ('twelvepercent', models.CharField(max_length=400)),
                ('graduateschool', models.CharField(max_length=400)),
                ('graduatepassing', models.CharField(max_length=400)),
                ('graduatepercent', models.CharField(max_length=400)),
                ('expereience', models.CharField(max_length=1000)),
                ('projects', models.CharField(max_length=2000)),
                ('profileId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
